// <auto-generated />
using System;
using System.Text.Json;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260504194345_FinalMatchHistorySync")]
    partial class FinalMatchHistorySync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("RoundNumber")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("Api.Entities.MatchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatchStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerOneId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerOneUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerTwoId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerTwoUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TournamentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("MatchHistories", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Api.Entities.UserGame", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<short>("PlayerPlacement")
                        .HasColumnType("smallint");

                    b.Property<short>("PlayerTurn")
                        .HasColumnType("smallint");

                    b.HasKey("UserId", "GameId");

                    b.ToTable("UserRound", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Guest", b =>
                {
                    b.HasBaseType("Api.Entities.User");

                    b.HasDiscriminator().HasValue("Guest");
                });

            modelBuilder.Entity("Api.Entities.RegisteredUser", b =>
                {
                    b.HasBaseType("Api.Entities.User");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("RegisteredUser");
                });

            modelBuilder.Entity("Api.Entities.MatchHistory", b =>
                {
                    b.OwnsMany("Api.Entities.Move", "Moves", b1 =>
                        {
                            b1.Property<Guid>("MatchHistoryId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<JsonElement>("MoveData")
                                .HasColumnType("jsonb");

                            b1.Property<DateTime>("PlayedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("MatchHistoryId", "__synthesizedOrdinal");

                            b1.ToTable("MatchHistories");

                            b1.ToJson("Moves");

                            b1.WithOwner()
                                .HasForeignKey("MatchHistoryId");
                        });

                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
